name: Main

on:
  push:
    branches:
      - main

env:
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_DEBUG:     ${{ vars.KOSLI_DEBUG }}
  KOSLI_DRY_RUN:   ${{ vars.KOSLI_DRY_RUN }}
  KOSLI_HOST:      ${{ vars.KOSLI_HOST }}
  KOSLI_ORG:       ${{ vars.KOSLI_ORG }}
  KOSLI_FLOW:      ${{ github.event.repository.name }}-ci
  KOSLI_TRAIL:     ${{ github.sha}}
  SERVICE_NAME:    ${{ github.event.repository.name }}  # eg golden-ledger

jobs:
  setup:
    needs: []
    if: ${{ github.event.repository.name != 'base' }}
    runs-on: ubuntu-latest
    outputs:
      repo_name:    ${{ steps.vars.outputs.repo_name }}
      service_name: ${{ steps.vars.outputs.service_name }}
      registry:     ${{ steps.vars.outputs.registry }}
      image_tag:    ${{ steps.vars.outputs.image_tag }}
      image_name:   ${{ steps.vars.outputs.image_name }}
      kosli_flow:   ${{ steps.vars.outputs.kosli_flow }}
      kosli_trail:  ${{ steps.vars.outputs.kosli_trail }}
      repo_json:    ${{ steps.setup-repo-json.outputs.repo_json }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Prepare outputs
        id: vars
        run: |
          REGISTRY="ghcr.io/kosli-demo"
          IMAGE_TAG="${GITHUB_SHA:0:7}"
          IMAGE_NAME="${REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG}"
          {
            echo "repo_name=${{ github.event.repository.name }}"
            echo "service_name=${SERVICE_NAME}"
            echo "registry=${REGISTRY}"
            echo "image_tag=${IMAGE_TAG}"
            echo "image_name=${IMAGE_NAME}"
            echo "kosli_flow=${KOSLI_FLOW}"
            echo "kosli_trail=${KOSLI_TRAIL}"
          } >> "${GITHUB_OUTPUT}"

      - uses: actions/checkout@v6

      - name: Setup this repos json
        id: setup-repo-json
        run: |
          REPO="${{ github.event.repository.name }}"
          FILTER=".[] | select(.repo_name == \"${REPO}\")"
          REPO_JSON="$(jq --compact-output "${FILTER}" data/all-repos.json)"
          echo "repo_json=${REPO_JSON}" >> ${GITHUB_OUTPUT}

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v3
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create Kosli Flow
        run:
          kosli create flow "${KOSLI_FLOW}"

      - name: Begin Kosli Trail
        run:
          kosli begin trail "${KOSLI_TRAIL}"

      - name: Write Trail URL to GitHub Step Summary
        run: |
          url="${KOSLI_HOST}/${KOSLI_ORG}/flows/${KOSLI_FLOW}/trails/${KOSLI_TRAIL}"
          echo "[Kosli Trail](${url})" > "${GITHUB_STEP_SUMMARY}"

  build-image:
    needs: [setup]
    uses: kosli-demo/actions/.github/workflows/secure-docker-build.yml@main
    with:
      checkout_repository: kosli-demo/${{ needs.setup.outputs.repo_name }}
      checkout_ref: ${{ github.sha }}
      checkout_fetch_depth: 1
      image_name: ${{ needs.setup.outputs.registry }}/${{ needs.setup.outputs.service_name }}
      image_tag: ${{ needs.setup.outputs.image_tag }}
      image_build_args: |
        COMMIT_SHA=${{ github.sha }}
      kosli_flow: ${{ needs.setup.outputs.kosli_flow }}
      kosli_trail: ${{ needs.setup.outputs.kosli_trail }}
      kosli_reference_name: artifact
      attest_to_kosli: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      kosli_api_token: ${{ secrets.KOSLI_API_TOKEN }}
